url: raohy.github.io
baseurl: ""
# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
permalink: /:year/:month/:day/:title.html

kramdown:
  input: GFM
